;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        coffee-indent-shift-left
        coffee-newline-and-indent
        delete-horizontal-space
        electric-newline-and-maybe-indent
        end-of-buffer
        handle-switch-frame
        ido-switch-buffer
        indent-for-tab-command
        isearch-repeat-forward
        kill-region
        mouse-set-region
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-newline
        paredit-splice-sexp-killing-backward
        sh-assignment
        subword-left
        tagedit-forward-slurp-tag
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        make-frame
        previous-buffer
        projectile-find-file
        tagedit-convolute-tags
        ))
